WELCOME TO NUMPY

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,4,5,23])

In [3]:
myarr

array([ 3,  4,  5, 23])

In [4]:
print(myarr)

[ 3  4  5 23]


In [5]:
myarr[0]

3

In [6]:
myarr[3]

23

In [7]:
myarr.dtype

dtype('int32')

In [8]:
myarr[0]

3

In [9]:
myarr[0] = 576

In [10]:
print(myarr)

[576   4   5  23]


In [11]:
array_list = np.array([3, 4,  6 ,23])
array_tuple = np.array((3, 4,  6 ,23))


In [12]:
array_list

array([ 3,  4,  6, 23])

In [13]:
array_tuple

array([ 3,  4,  6, 23])

**INTRINIC NUMPY ARRAY CREATIONS**

In [14]:
array_arange = np.arange(0, 10, 2)

In [15]:
array_arange

array([0, 2, 4, 6, 8])

In [16]:
array_linspace = np.linspace(0, 1, 5) 

In [17]:
array_linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
array_zeros = np.zeros((2, 3))  # 2x3 array of zeros
array_ones = np.ones((2, 3)) # 2x3 array of ones

In [19]:
print(array_zeros)  # 2x3 array of zeros

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
array_zeos = np.zeros((2, 3, 2))

In [22]:
print(array_zeos)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [23]:
array_full = np.full((2, 3), 7)  # 2x3 array filled with 7

In [24]:
array_full

array([[7, 7, 7],
       [7, 7, 7]])

In [25]:
array_zeos.shape

(2, 3, 2)

In [26]:
identity_matrix = np.eye(3)  # 3x3 identity matrix


In [27]:
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
array_diag = np.diag([1, 2, 3])  # diagonal matrix with [1, 2, 3] on the diagonal


In [29]:
print(array_diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [30]:
random_array = np.random.random((2, 3))  # 2x3 array with random floats in [0.0, 1.0)
random_int_array = np.random.randint(0, 10, (2, 3))  # 2x3 array with random integers in [0, 10)


In [31]:
print(random_array)

[[0.42751247 0.42483072 0.38551929]
 [0.2230743  0.34833239 0.81072725]]


In [32]:
print(random_array)

[[0.42751247 0.42483072 0.38551929]
 [0.2230743  0.34833239 0.81072725]]


In [33]:
print(random_int_array)

[[5 6 5]
 [9 7 6]]


In [34]:
print(random_int_array)

[[5 6 5]
 [9 7 6]]


In [35]:
empty_array = np.empty((2, 3))  # 2x3 array with uninitialized values


In [36]:
print(empty_array)

[[0.42751247 0.42483072 0.38551929]
 [0.2230743  0.34833239 0.81072725]]


In [37]:
a = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_a = np.zeros_like(a)  # array with same shape as 'a' filled with zeros
ones_like_a = np.ones_like(a)    # array with same shape as 'a' filled with ones
full_like_a = np.full_like(a, 7) # array with same shape as 'a' filled with 7


In [38]:
print(a)

[[1 2 3]
 [4 5 6]]


In [39]:
print(zeros_like_a)

[[0 0 0]
 [0 0 0]]


In [40]:
print(ones_like_a)

[[1 1 1]
 [1 1 1]]


In [41]:
print(full_like_a)

[[7 7 7]
 [7 7 7]]


***ARRAY CREATIONS: CONVERSION FROM OTHER PYTHON STRUCTURES***

In [42]:
listarray = np.array([[1,  3, 2], [4, 78, 36]])

In [43]:
listarray

array([[ 1,  3,  2],
       [ 4, 78, 36]])

In [44]:
listarray.dtype

dtype('int32')

In [45]:
listarray.shape

(2, 3)

In [46]:
listarray.size

6

In [47]:
# u can change the the elements as well 

In [48]:
zer = np.zeros((2, 5))

In [49]:
zer

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.array({34 ,67})

array({34, 67}, dtype=object)

In [51]:
array_arange = np.arange(0, 10)

In [52]:
array_arnge = np.arange(0, 10, 3)

In [53]:
array_arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
array_arnge

array([0, 3, 6, 9])

In [55]:
array_linspace = np.linspace(1, 4, 11) 

In [56]:
array_linspace

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. ])

In [57]:
emp = np.empty((4, 6))

In [58]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 1.60216183e-306, 7.56602523e-307,
        3.56043054e-307, 1.37961641e-306, 2.22518251e-306],
       [1.33511969e-306, 6.23037317e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 1.60221072e-306,
        1.11261027e-306, 8.34420522e-308, 1.42410974e-306]])

In [59]:
emp_like = np.empty_like(array_linspace)

In [60]:
emp_like

array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. ])

In [61]:
ide = np.identity(45)

In [62]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [63]:
print(ide)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [64]:
ide.shape

(45, 45)

In [65]:
arr = np.arange(99)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [67]:
arr.reshape(3, 33) # convertion of the 1D to 2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [68]:
arr = np.arange(100)

In [69]:
arr.reshape(4, 5, 5) #converting 1D to 3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [70]:
arr # U can see that original array didnt chanege

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [71]:
arr = arr.reshape(25, 4) # Now this will change array

In [72]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [73]:
arr.ravel

<function ndarray.ravel>

In [74]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [75]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [76]:
arr = arr.ravel() #Remake to 1D array

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [78]:
arr.shape

(100,)

NUMPY AXIS 

In [79]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [80]:
ar = np.array(x)

In [81]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [82]:
ar.sum(axis = 0) #column wise summation

array([12,  8,  9])

In [83]:
ar.sum(axis = 1) # row wise summation

array([ 6, 15,  8])

In [84]:
ar.T # Makes the transpose of the aray

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [85]:
ar.flat

In [86]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [87]:
arr.ndim

1

In [88]:
ar.size

9

In [89]:
ar.nbytes

36

In [90]:
ar.nbytes

36

In [91]:
one = np.array([1, 2, 345, 0])

In [92]:
one.argmax() # returns the index of the maximum element in the array

2

In [93]:
one.argmin()

3

In [94]:
one.argsort() #returns the sorted indexes

array([3, 0, 1, 2], dtype=int64)

In [95]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [96]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [97]:
ar.argmin() #gives index after convertng it into flat

8

In [98]:
ar.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [99]:
ar.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [100]:
ar.reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [101]:
ar2 = np.array([[3, 6, 2], [6, 8, 2], [1, 5, 6]])

In [102]:
ar + ar2

array([[ 4,  8,  5],
       [10, 13,  8],
       [ 8,  6,  6]])

In [103]:
 ar * ar2

array([[ 3, 12,  6],
       [24, 40, 12],
       [ 7,  5,  0]])

In [104]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [105]:
ar2


array([[3, 6, 2],
       [6, 8, 2],
       [1, 5, 6]])

In [106]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [107]:
ar.sum()

29

In [108]:
ar2.sum()

39

In [109]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [110]:
np.where(ar>=5)

(array([1, 1, 2], dtype=int64), array([1, 2, 0], dtype=int64))

In [111]:
type(np.where(ar>=5))

tuple

In [112]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [113]:
import sys

In [114]:
py_ar = [0, 4, 55 ,2]

In [115]:
np_ar = np.array(py_ar)

In [116]:
sys.getsizeof(1) * len(py_ar)

112

In [117]:
np_ar.itemsize * np_ar.size

16